### ISSUE TITLE
Maliciosamente delicioso

### ISSUE THREAD

**Issue by destroller22** [demixitho3/BugTracker-Monster#102]
Link Wowhead: https://es.wowhead.com/quest=27587/maliciosamente-delicioso
La misión proporciona un objeto, el cual debiera dar respiración bajo el agua, sin embargo, aún teniendo el buff del objeto, la barra de respiración aparece y por ende, no se puede respirar bajo el agua.

https://cata-twinhead.twinstar.cz/?item=62795

**Comment by elerendon** [comment]
la mision y el item funcionan correctamente, no te ahogas sin necesidad del item mencionado y usandolo igual no te ahogas
