### ISSUE TITLE
npc icc

### ISSUE THREAD

**Issue by destroller22** [demixitho3/BugTracker-Monster#108]
Se bugueo el boss y el chamo lo salvó.
Benditos sean esos chamis que salvan la mentira.
Si el chami es dps mejor que mejor.
No lo borren.

Siempre pasa, ese el npc (no recuerdo su nombre) nunca da ress

**Comment by elerendon** [comment]
se necesita link de npc, id o algo fotos o algo para poder ubicar este bug
