### ISSUE TITLE
Bolsa de especias pequeña 

### ISSUE THREAD

**Issue by destroller22** [demixitho3/BugTracker-Monster#115]
La Bolsa de especias pequeña https://db.wowlatinoamerica.com/?item=44113#contains deberia de dar https://db.wowlatinoamerica.com/?item=44113#contains pero no los da. esto hace que sea mas difícil conseguir todas las recetas y el gorro de cocina de dalaran

**Comment by elerendon** [comment]
tiene un porcentaje bajo por eso tienes que tener suerte
