### ISSUE TITLE
Bug en Vehiculo Horda 

### ISSUE THREAD

**Issue by destroller22** [demixitho3/BugTracker-Monster#132]
Bug con PNJ en Vehiculo Horda en Azshara

En la Zona de Azshara (https://es.wowhead.com/azshara), el uso del Vehículo del Maestro de Vuelo de la Horda: Friz Girasuelo (https://es.wowhead.com/npc=37005/friz-girasuelo), no puede usarse a menos que seas nivel 55 o superior, debido a que el PNJ Consorte Tronatesta (https://es.wowhead.com/npc=6380/consorte-tronatesta), esta oculto debajo de la zona para usar el Vehiculo y ataca al jugador que se acerca a el, ademas de que es una zona para PJ de nivel 10-20, el PNJ es de nivel 55.

**Comment by elerendon** [comment]
npc eliminado
