### ISSUE TITLE
Bug en mision [No puedes acabar con ellos solo](Part 1 of 3)

### ISSUE THREAD

**Issue by alesfre** [demixitho3/BugTracker-Monster#139]
No puedo avanzar en la mision de los hombres lobo, cuando uso el barril, solo se usa una ves y desaparece , y no puedo hacer los 4 que pide la mision.
https://es.wowhead.com/quest=14348/no-puedes-acabar-con-ellos-solo

**Comment by elerendon** [comment]
esta mision funciona correctamente solo tienes que tomar los barriles para poder usar contra las abominaciones
