### ISSUE TITLE
mision : Un ritual de llamas

### ISSUE THREAD

**Issue by ZheroGm** [demixitho3/BugTracker-Monster#152]
ID de mision : 29195
descripcion: Lucha contra las oleadas de invasores carbonizados en Cresta Nordune hasta que el portal se abra.
problema: al realizar la mision los elementales y las oleadas salen, pero las guias y demas al pasar ya solo maximo de 3 min ya se completa, pero matando mas de 1 hora no pasa nada y siguen sin completarse.
solucion: poner la mision autocompletable para poder continuar con la cadema de misiones de Frente de Magma.
![image](https://user-images.githubusercontent.com/89149102/129925013-b0ab9844-8633-4456-b924-092c4675daf9.png)

**Comment by elerendon** [comment]
link de misión https://es.wowhead.com/quest=29195/un-ritual-de-llamas
link de youtube como deberia funcionar https://www.youtube.com/watch?v=216lIzylmaw&ab_channel=MonoRadioactivo
