### ISSUE TITLE
Llego la hora de las presentaciones

### ISSUE THREAD

**Issue by joseca375** [demixitho3/BugTracker-Monster#51]
El estandarte de Koroth, al invocar al ogro este aparece sin problemas, pero es imposible matarlo con el nivel y las armaduras que te permiten el juego, e buscado por todo el paga otras misiones para desbloquear el paso pero no encuentro ninguna, por favor se podria ajustar la vida de este o completar dar la mision como cumplida? mi jugador se llama Cataclysmm, desde ya muchas gracias

**Comment by demixitho3** [comment]
necesitamos id del npc, imagen, y zona para poder ir a ubicar al npc

**Comment by Fabiduarte** [comment]
ya fue reportado.
