### ISSUE TITLE
No hay maestro de hipogrifos en El Exodar 

### ISSUE THREAD

**Issue by destroller22** [demixitho3/BugTracker-Monster#65]
Link WoWHead: https://es.wowhead.com/npc=17555/stephanos#screenshots
El NPC no aparece en donde marca el minimapa, y se comprueba la ubicación con la misión https://es.wowhead.com/quest=9606/regresa-junto-a-la-cuidadora-chellan
Link adicional: https://cata-twinhead.twinstar.cz/?npc=17555#.

**Comment by demixitho3** [comment]
![WoW_X5XQSjqfan](https://user-images.githubusercontent.com/42742610/127009405-08f273fd-72ff-4cc7-b2dc-3bd60e1c923f.png)
aca vemos que si está el npc
