### ISSUE TITLE
misión  Líder de la manada 

### ISSUE THREAD

**Issue by demixitho3** [demixitho3/BugTracker-Monster#73]
https://es.wowhead.com/quest=14386/l%C3%ADder-de-la-manada
el silbato solo se debe activar al seleccionar al npc objetivo pero se activa sin necesidad de targetearlo como muestro en la imagen
![image](https://user-images.githubusercontent.com/42742610/127368426-0dbd4d47-0953-4c69-9da7-8f23da0d83f9.png)
sin siquiera acercarte al objetivo te marca como completada 
![image](https://user-images.githubusercontent.com/42742610/127368834-d0c511cc-0ace-446a-b9d5-7710e0a6cc2a.png)
aquí un video de como debería funcionar
https://www.youtube.com/watch?v=5tCF-pbSgTE&ab_channel=SuperFandeWoW

**Comment by elerendon** [comment]
![image](https://user-images.githubusercontent.com/42742610/127649231-77a92a46-42f8-4e35-abc6-4d86c647efe6.png)
sigue bug la misión al precionar el silbato no ocurre absolutamente nada y deberian salir perros a atacar a la forestal NPC "36312"
el silbato solo debe activarse al seleccionar a dicho NPC como muestra en el video
https://www.youtube.com/watch?v=5tCF-pbSgTE&ab_channel=SuperFandeWoW
