### ISSUE TITLE
Talentos sutileza

### ISSUE THREAD

**Issue by Mayner123** [demixitho3/BugTracker-Monster#74]
El daño de sutileza del rogué anda haciendo mucho daño necesita testear nuevamente y bajar el daño porq andan matando de 2 golpes

**Comment by Fabiduarte** [comment]
Tener una cuenta en github:
Guía para crear una cuenta https://www.youtube.com/watch?v=ODjyWXUFa7M
Encontrar un error dentro del juego
Al momento de subir el reporte debe de cumplir las reglas, caso contrario el reporte será cerrado y desechado.
Clic en "Issues":
Clic en New Issues:
Llenar los campos solicitados y clic en submit:
Reglas para subir reportes:
Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.
