### ISSUE TITLE
Mision Planes diabolicos!

### ISSUE THREAD

**Issue by destroller22** [demixitho3/BugTracker-Monster#80]
les quería compartir un bug que he encontrado en una mision que se recoje por loot, llamada Planes diabolicos: https://es.wowhead.com/item=23780/planes-diab%C3%B3licos
La cual permite acceder a esta misión:
https://es.wowhead.com/quest=26443/planes-diab%C3%B3licos

**Comment by elerendon** [comment]
esa misión fué retirada en cataclismo ya no existe
