### ISSUE TITLE
Quest id 10526 de Montañas Filospada

### ISSUE THREAD

**Issue by destroller22** [demixitho3/BugTracker-Monster#81]
En esta quest se debe tomar un contenedor que invoca al Npc que dropea el item de la misma...pero al usar el contenedor dicho npc=21319/Gor Tripuriosa no aparece y se bugea el combate...gracias...https://es.wowhead.com/item=30435/la-punta-de-trueno...sin ella no se puede seguir y tampoco sacar logro.

**Comment by elerendon** [comment]
![image](https://user-images.githubusercontent.com/42742610/127652604-2d9fc6b3-a09c-4fe2-8b96-9651f90a4687.png)
si funciona normal

**Comment by elerendon** [comment]
![image](https://user-images.githubusercontent.com/42742610/127653130-986743ef-e499-49c3-9bed-381edb0465bf.png)
loot corregido
