### ISSUE TITLE
[El emisario] 

### ISSUE THREAD

**Issue by destroller22** [demixitho3/BugTracker-Monster#98]
como se hace: https://www.youtube.com/watch?v=6__yZ5VmQGQ
wow head : https://es.wowhead.com/quest=11626/el-emisario

Al tirar la "lanza" que dan para matar el npc, hace daño correctamente, pero el npc se cura y se hace imposible completarla

**Comment by elerendon** [comment]
el npc funciona correctamente y la mision se realiza correctamente
